### ISSUE TITLE
Question: Can you have a property validate using another validator?

### ISSUE THREAD

**Issue by ib-jamesp** [deva666/KValidation#4]
Sorry I haven't started using the framework, however wanted to ask a quick question before I do! 

Given a class such as :
`
 data class Parent(
   val child: ChildClass
) {
}
`

Can you use a validator that has 
`
validator.forProperty { p -> p.child } -> ChildValidator()
`

**Comment by deva666** [comment]
One way of using it would be something like this ...
```
validator.forProperty { p -> p.child } rules {
   mustBe(it.innerValidator.isValid())
}
```

And `ChildClass` would have to have an `InnerValidator` as property
